In [11]:
import pandas as pd
import numpy as np
import dateutil
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [2]:
import warnings
warnings.filterwarnings('ignore')
pd.set_option('max_column', None)

In [3]:
tel=pd.read_csv(r'C:\Users\Jakinda\Documents\Python Scripts\10Academy\Week1\data\Week1_challenge_data_source(CSV).csv')
tel.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,42.0,5.0,23.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,NaN,NaN,NaN,NaN,NaN,NaN,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),NaN,NaN,NaN,NaN,NaN,NaN,971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),NaN,NaN,NaN,NaN,NaN,NaN,751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,NaN,NaN,44.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,3330.0,37882.0,1.321510e+09,undefined,undefined,NaN,NaN,NaN,NaN,NaN,NaN,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,NaN,NaN,NaN,NaN,NaN,NaN,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [4]:
tel.columns.tolist()

['Bearer Id',
 'Start',
 'Start ms',
 'End',
 'End ms',
 'Dur. (ms)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last Location Name',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'TCP DL Retrans. Vol (Bytes)',
 'TCP UL Retrans. Vol (Bytes)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'HTTP DL (Bytes)',
 'HTTP UL (Bytes)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur. (ms).1',
 'Handset Manufacturer',
 'Handset Type',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

In [5]:
tel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

In [16]:
#convert date time from string
tel['Start'] = pd.to_datetime(tel['Start'],format = '%b %d %Y %H:%M',errors='ignore')
tel['End'] = pd.to_datetime(tel['End'],format = '%b %d %Y %H:%M',errors='ignore')

#df['date'] = pd.to_datetime(df['date'], errors='ignore')
#pd.to_datetime(df['date'], format="%Y-%d-%m %H:%M:%S"

In [19]:
tel['Start'] = pd.to_datetime(tel['Start'])
tel['End'] = pd.to_datetime(tel['End'])

In [21]:
tel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  datetime64[ns]
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  datetime64[ns]
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: datetime64[ns](2), float64(50), object(3)
memory usage: 62.9+ MB

In [64]:
print(f" There are {tel.shape[0]} rows and {tel.shape[1]} columns")

 There are 150001 rows and 55 columns

In [6]:
#tel.nunique(axis=0)

In [7]:
#tel.describe().apply(lambda s: s.apply(lambda x: format(x, 'f')))

In [65]:
# how many missing values exist or better still what is the % of missing values in the dataset?
def percent_missing(df):

    # Calculate total number of cells in dataframe
    totalCells = np.product(df.shape)

    # Count number of missing values per column
    missingCount = df.isnull().sum()

    # Calculate total number of missing values
    totalMissing = missingCount.sum()

    # Calculate percentage of missing values
    print("The telecom dataset contains", round(((totalMissing/totalCells) * 100), 2), "%", "missing values.")

percent_missing(tel)

The telecom dataset contains 12.5 % missing values.

In [66]:
tel.isna().sum()

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [67]:
# drop columns with more than 30% missing values
NA_val = tel.isna().sum()
def na_filter(na, threshold = .3): #only select variables that passees the threshold
    col_pass = []
    for i in na.keys():
        if na[i]/tel.shape[0]<threshold:
            col_pass.append(i)
    return col_pass
tel = tel[na_filter(NA_val)]
tel.columns.tolist()

['Bearer Id',
 'Start',
 'Start ms',
 'End',
 'End ms',
 'Dur. (ms)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last Location Name',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur. (ms).1',
 'Handset Manufacturer',
 'Handset Type',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

In [68]:
print(f" There are {tel.shape[0]} rows and {tel.shape[1]} columns")

 There are 150001 rows and 45 columns

In [69]:
tel['Handset Type'].value_counts()[:10]

Huawei B528S-23A                19752
Apple iPhone 6S (A1688)          9419
Apple iPhone 6 (A1586)           9023
undefined                        8987
Apple iPhone 7 (A1778)           6326
Apple iPhone Se (A1723)          5187
Apple iPhone 8 (A1905)           4993
Apple iPhone Xr (A2105)          4568
Samsung Galaxy S8 (Sm-G950F)     4520
Apple iPhone X (A1901)           3813
Name: Handset Type, dtype: int64

In [70]:
tel['Handset Manufacturer'].value_counts()[:5]

Apple                            59565
Samsung                          40839
Huawei                           34423
undefined                         8987
Sony Mobile Communications Ab      980
Name: Handset Manufacturer, dtype: int64

In [71]:
tel.groupby(['Handset Manufacturer'])['Handset Type'].value_counts().nlargest()

Handset Manufacturer  Handset Type
Huawei                Huawei B528S-23A           19752
Apple                 Apple iPhone 6S (A1688)     9419
                      Apple iPhone 6 (A1586)      9023
undefined             undefined                   8987
Apple                 Apple iPhone 7 (A1778)      6326
Name: Handset Type, dtype: int64

In [72]:
tel['Bearer Id'].value_counts()

1.304243e+19    16
1.304243e+19    10
1.304243e+19     9
1.304243e+19     9
1.304243e+19     9
                ..
7.349883e+18     1
7.277826e+18     1
1.304243e+19     1
7.277826e+18     1
7.277826e+18     1
Name: Bearer Id, Length: 134708, dtype: int64

In [73]:
def find_agg(df:pd.DataFrame, agg_column:str, agg_metric:str, col_name:str, top:int, order=False )->pd.DataFrame:
    
    new_df = df.groupby(agg_column)[agg_column].agg(agg_metric).reset_index(name=col_name).\
                        sort_values(by=col_name, ascending=order)[:top]
    
    return new_df

In [74]:
number_of_xDRsessions =find_agg(tel,'Bearer Id','count','number of xDR sessions per user',10)
number_of_xDRsessions

           Bearer Id  number of xDR sessions per user
103378  1.304243e+19                               16
88125   1.304243e+19                               10
97305   1.304243e+19                                9
101588  1.304243e+19                                9
93908   1.304243e+19                                9
103736  1.304243e+19                                9
99394   1.304243e+19                                8
119993  1.311448e+19                                8
99790   1.304243e+19                                8
83743   1.304243e+19                                8

In [ ]:
tel.groupby('MSISDN/Number', as_index=False).agg({"Bearer Id": "sum"})

In [75]:
tel.groupby('MSISDN/Number', as_index=False).agg({"Dur. (ms)": "sum"})

           Bearer Id  Dur. (ms)
0       6.917538e+18    24534.0
1       6.917538e+18    21489.0
2       6.917538e+18    27786.0
3       6.917538e+18    15635.0
4       6.917538e+18    24264.0
...              ...        ...
134703  1.318654e+19    80024.0
134704  1.318654e+19   145291.0
134705  1.318654e+19    86399.0
134706  1.318654e+19    86399.0
134707  1.318654e+19   103113.0

[134708 rows x 2 columns]

In [84]:
tel.groupby(
   ['MSISDN/Number']
).agg(
    {
          'Total UL (Bytes)':sum,
         'Total DL (Bytes)':sum,
    }
)

              Total UL (Bytes)  Total DL (Bytes)
Bearer Id
6.917538e+18        41704610.0       500721999.0
6.917538e+18        38693596.0       709549265.0
6.917538e+18        15548926.0       854465860.0
6.917538e+18        49605688.0       825786510.0
6.917538e+18        21983463.0       624957763.0
...                        ...               ...
1.318654e+19        35412664.0       145293140.0
1.318654e+19        36189587.0       387001634.0
1.318654e+19        35919460.0       872688792.0
1.318654e+19        40877676.0       386355068.0
1.318654e+19        46147558.0       327212841.0

[134708 rows x 2 columns]

In [85]:
tel.groupby(
   ['MSISDN/Number']
).agg(
    {
         'Social Media DL (Bytes)':sum,
         'Social Media UL (Bytes)':sum,
         'Google DL (Bytes)':sum,
         'Google UL (Bytes)':sum,
         'Email DL (Bytes)':sum,
         'Email UL (Bytes)':sum,
         'Youtube DL (Bytes)':sum,
         'Youtube UL (Bytes)':sum,
         'Netflix DL (Bytes)':sum,
         'Netflix UL (Bytes)':sum,
         'Gaming DL (Bytes)':sum,
         'Gaming UL (Bytes)':sum,
         'Other DL (Bytes)':sum,
         'Other UL (Bytes)':sum,
         
             
        
    }
)

,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes)
Bearer Id,,,,,,,,,,,,,,
6.917538e+18,2404741.0,2410.0,5791591.0,2871336.0,782388.0,806920.0,6139644.0,2071526.0,19494278.0,14668354.0,466109357.0,5333340.0,670751043.0,15950724.0
6.917538e+18,2478607.0,11936.0,3605446.0,2825198.0,446376.0,525108.0,10281221.0,18119976.0,19455048.0,10631652.0,673282567.0,2670856.0,501608458.0,3908870.0
6.917538e+18,944612.0,2827.0,10373157.0,56392.0,128003.0,34038.0,5385159.0,4295851.0,15755839.0,1300571.0,821879090.0,8521398.0,472846860.0,1337849.0
6.917538e+18,1817239.0,19827.0,269988.0,3696393.0,3191192.0,896670.0,12347020.0,11089528.0,2859358.0,1738176.0,805301713.0,16257481.0,24303797.0,15907613.0
6.917538e+18,1867318.0,18928.0,1689296.0,195216.0,740633.0,590043.0,15231815.0,8401567.0,21563985.0,2817981.0,583864716.0,6992868.0,685122214.0,2966860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1.318654e+19,3240226.0,38284.0,2036152.0,2271168.0,2410615.0,387548.0,12404964.0,4343114.0,11108134.0,21649273.0,114093049.0,2834548.0,695881178.0,3888729.0
1.318654e+19,3062671.0,48953.0,9363661.0,4001970.0,2192057.0,866373.0,22147919.0,2152449.0,21468525.0,8603105.0,328766801.0,7569327.0,371261255.0,12947410.0
1.318654e+19,720996.0,42836.0,1541915.0,2100839.0,2315638.0,839789.0,11879062.0,1290963.0,22596930.0,11943452.0,833634251.0,10607174.0,697260277.0,9094407.0
1.318654e+19,2492460.0,39905.0,11318188.0,466218.0,2612190.0,618629.0,22163800.0,16763435.0,9522397.0,8346624.0,338246033.0,1845068.0,17385489.0,12797797.0
1.318654e+19,1314234.0,27938.0,6969652.0,3756009.0,3317462.0,408257.0,12099319.0,1636122.0,9992219.0,17624886.0,293519955.0,16295588.0,440290470.0,6398758.0

In [80]:
tel['Bearer Id'] = tel['Bearer Id'].fillna(tel['Bearer Id'].mode()[0])
tel['IMSI'] = tel['IMSI'].fillna(tel['IMSI'].mode()[0])
tel['MSISDN/Number'] = tel['MSISDN/Number'].fillna(tel['MSISDN/Number'].mode()[0])
tel['IMEI'] = tel['IMEI'].fillna(tel['IMEI'].mode()[0])

In [99]:
numerical_column = tel [['Total UL (Bytes)','Total DL (Bytes)']]

In [100]:
z=np.abs(stats.zscore(numerical_column))
print(z)

[[nan nan]
 [nan nan]
 [nan nan]
 ...
 [nan nan]
 [nan nan]
 [nan nan]]

In [81]:
tel.isna().sum()

Bearer Id                             0
Start                                 1
Start ms                              1
End                                   1
End ms                                1
Dur. (ms)                             1
IMSI                                  0
MSISDN/Number                         0
IMEI                                  0
Last Location Name                 1153
Avg RTT DL (ms)                   27829
Avg RTT UL (ms)                   27812
Avg Bearer TP DL (kbps)               1
Avg Bearer TP UL (kbps)               1
DL TP < 50 Kbps (%)                 754
50 Kbps < DL TP < 250 Kbps (%)      754
250 Kbps < DL TP < 1 Mbps (%)       754
DL TP > 1 Mbps (%)                  754
UL TP < 10 Kbps (%)                 792
10 Kbps < UL TP < 50 Kbps (%)       792
50 Kbps < UL TP < 300 Kbps (%)      792
UL TP > 300 Kbps (%)                792
Activity Duration DL (ms)             1
Activity Duration UL (ms)             1
Dur. (ms).1                           1
Handset Manufacturer                572
Handset Type                        572
Nb of sec with Vol DL < 6250B       755
Nb of sec with Vol UL < 1250B       793
Social Media DL (Bytes)               0
Social Media UL (Bytes)               0
Google DL (Bytes)                     0
Google UL (Bytes)                     0
Email DL (Bytes)                      0
Email UL (Bytes)                      0
Youtube DL (Bytes)                    0
Youtube UL (Bytes)                    0
Netflix DL (Bytes)                    0
Netflix UL (Bytes)                    0
Gaming DL (Bytes)                     0
Gaming UL (Bytes)                     0
Other DL (Bytes)                      0
Other UL (Bytes)                      0
Total UL (Bytes)                      1
Total DL (Bytes)                      1
dtype: int64

In [26]:
tel.mean()

Bearer Id                         1.013887e+19
Start ms                          4.991882e+02
End ms                            4.988009e+02
Dur. (ms)                         1.046086e+05
IMSI                              2.082016e+14
MSISDN/Number                     4.188282e+10
IMEI                              4.847455e+13
Avg RTT DL (ms)                   1.097957e+02
Avg RTT UL (ms)                   1.766288e+01
Avg Bearer TP DL (kbps)           1.330005e+04
Avg Bearer TP UL (kbps)           1.770429e+03
DL TP < 50 Kbps (%)               9.284475e+01
50 Kbps < DL TP < 250 Kbps (%)    3.069355e+00
250 Kbps < DL TP < 1 Mbps (%)     1.717341e+00
DL TP > 1 Mbps (%)                1.609654e+00
UL TP < 10 Kbps (%)               9.853014e+01
10 Kbps < UL TP < 50 Kbps (%)     7.767494e-01
50 Kbps < UL TP < 300 Kbps (%)    1.479871e-01
UL TP > 300 Kbps (%)              7.892285e-02
Activity Duration DL (ms)         1.829177e+06
Activity Duration UL (ms)         1.408880e+06
Dur. (ms).1                       1.046091e+08
Nb of sec with Vol DL < 6250B     3.719788e+03
Nb of sec with Vol UL < 1250B     4.022083e+03
Social Media DL (Bytes)           1.795322e+06
Social Media UL (Bytes)           3.292843e+04
Google DL (Bytes)                 5.750753e+06
Google UL (Bytes)                 2.056542e+06
Email DL (Bytes)                  1.791729e+06
Email UL (Bytes)                  4.673734e+05
Youtube DL (Bytes)                1.163407e+07
Youtube UL (Bytes)                1.100941e+07
Netflix DL (Bytes)                1.162685e+07
Netflix UL (Bytes)                1.100175e+07
Gaming DL (Bytes)                 4.220447e+08
Gaming UL (Bytes)                 8.288398e+06
Other DL (Bytes)                  4.211005e+08
Other UL (Bytes)                  8.264799e+06
Total UL (Bytes)                  4.112121e+07
Total DL (Bytes)                  4.546434e+08
dtype: float64

In [42]:
tel = tel.fillna(tel.mean())

In [43]:
tel.isna().sum()

Bearer Id                            0
Start                                1
Start ms                             0
End                                  1
End ms                               0
Dur. (ms)                            0
IMSI                                 0
MSISDN/Number                        0
IMEI                                 0
Last Location Name                1153
Avg RTT DL (ms)                      0
Avg RTT UL (ms)                      0
Avg Bearer TP DL (kbps)              0
Avg Bearer TP UL (kbps)              0
DL TP < 50 Kbps (%)                  0
50 Kbps < DL TP < 250 Kbps (%)       0
250 Kbps < DL TP < 1 Mbps (%)        0
DL TP > 1 Mbps (%)                   0
UL TP < 10 Kbps (%)                  0
10 Kbps < UL TP < 50 Kbps (%)        0
50 Kbps < UL TP < 300 Kbps (%)       0
UL TP > 300 Kbps (%)                 0
Activity Duration DL (ms)            0
Activity Duration UL (ms)            0
Dur. (ms).1                          0
Handset Manufacturer               572
Handset Type                       572
Nb of sec with Vol DL < 6250B        0
Nb of sec with Vol UL < 1250B        0
Social Media DL (Bytes)              0
Social Media UL (Bytes)              0
Google DL (Bytes)                    0
Google UL (Bytes)                    0
Email DL (Bytes)                     0
Email UL (Bytes)                     0
Youtube DL (Bytes)                   0
Youtube UL (Bytes)                   0
Netflix DL (Bytes)                   0
Netflix UL (Bytes)                   0
Gaming DL (Bytes)                    0
Gaming UL (Bytes)                    0
Other DL (Bytes)                     0
Other UL (Bytes)                     0
Total UL (Bytes)                     0
Total DL (Bytes)                     0
dtype: int64

In [45]:
def fix_missing_bfill(df, col):
    df[col] = df[col].fillna(method='bfill')
    return df[col]

In [47]:
tel['Handset Manufacturer'] = fix_missing_bfill(tel, 'Handset Manufacturer')
tel['Handset Type'] = fix_missing_bfill(tel, 'Handset Type')
tel['Last Location Name'] = fix_missing_bfill(tel, 'Last Location Name')

In [50]:
percent_missing(tel)

The telecom dataset contains 0.0 % missing values.

In [51]:
tel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 45 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Bearer Id                       150001 non-null  float64
 1   Start                           150000 non-null  object
 2   Start ms                        150001 non-null  float64
 3   End                             150000 non-null  object
 4   End ms                          150001 non-null  float64
 5   Dur. (ms)                       150001 non-null  float64
 6   IMSI                            150001 non-null  float64
 7   MSISDN/Number                   150001 non-null  float64
 8   IMEI                            150001 non-null  float64
 9   Last Location Name              150000 non-null  object
 10  Avg RTT DL (ms)                 150001 non-null  float64
 11  Avg RTT UL (ms)                 150001 non-null  float64
 12  Avg Bearer TP DL (kbps)         150001 non-null  float64
 13  Avg Bearer TP UL (kbps)         150001 non-null  float64
 14  DL TP < 50 Kbps (%)             150001 non-null  float64
 15  50 Kbps < DL TP < 250 Kbps (%)  150001 non-null  float64
 16  250 Kbps < DL TP < 1 Mbps (%)   150001 non-null  float64
 17  DL TP > 1 Mbps (%)              150001 non-null  float64
 18  UL TP < 10 Kbps (%)             150001 non-null  float64
 19  10 Kbps < UL TP < 50 Kbps (%)   150001 non-null  float64
 20  50 Kbps < UL TP < 300 Kbps (%)  150001 non-null  float64
 21  UL TP > 300 Kbps (%)            150001 non-null  float64
 22  Activity Duration DL (ms)       150001 non-null  float64
 23  Activity Duration UL (ms)       150001 non-null  float64
 24  Dur. (ms).1                     150001 non-null  float64
 25  Handset Manufacturer            150000 non-null  object
 26  Handset Type                    150000 non-null  object
 27  Nb of sec with Vol DL < 6250B   150001 non-null  float64
 28  Nb of sec with Vol UL < 1250B   150001 non-null  float64
 29  Social Media DL (Bytes)         150001 non-null  float64
 30  Social Media UL (Bytes)         150001 non-null  float64
 31  Google DL (Bytes)               150001 non-null  float64
 32  Google UL (Bytes)               150001 non-null  float64
 33  Email DL (Bytes)                150001 non-null  float64
 34  Email UL (Bytes)                150001 non-null  float64
 35  Youtube DL (Bytes)              150001 non-null  float64
 36  Youtube UL (Bytes)              150001 non-null  float64
 37  Netflix DL (Bytes)              150001 non-null  float64
 38  Netflix UL (Bytes)              150001 non-null  float64
 39  Gaming DL (Bytes)               150001 non-null  float64
 40  Gaming UL (Bytes)               150001 non-null  float64
 41  Other DL (Bytes)                150001 non-null  float64
 42  Other UL (Bytes)                150001 non-null  float64
 43  Total UL (Bytes)                150001 non-null  float64
 44  Total DL (Bytes)                150001 non-null  float64
dtypes: float64(40), object(5)
memory usage: 51.5+ MB

In [53]:
tel.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,1.500010e+05,150001.000000,150001.000000,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,150001.000000,150001.000000,150001.000000,150001.000000,150001.000000,150001.000000,150001.000000,150001.000000,150001.000000,150001.000000,150001.000000,150001.000000,1.500010e+05,1.500010e+05,1.500010e+05,150001.000000,150001.000000,1.500010e+05,150001.000000,1.500010e+05,1.500010e+05,1.500010e+05,150001.000000,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05
mean,1.013887e+19,499.188200,498.800880,1.046086e+05,2.082016e+14,4.188282e+10,4.847455e+13,109.795706,17.662883,13300.045927,1770.428647,92.844754,3.069355,1.717341,1.609654,98.530142,0.776749,0.147987,0.078923,1.829177e+06,1.408880e+06,1.046091e+08,3719.787552,4022.083454,1.795322e+06,32928.434380,5.750753e+06,2.056542e+06,1.791729e+06,467373.441940,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,4.112121e+07,4.546434e+08
std,2.883600e+18,288.610872,288.096693,8.103735e+04,2.144722e+10,2.438731e+12,2.237359e+13,559.342620,76.529933,23971.798635,4625.340082,13.005221,6.199592,4.149070,4.816738,4.622035,3.216651,1.620229,1.291972,5.696376e+06,4.643215e+06,8.103734e+07,9148.498009,10133.431600,1.035482e+06,19006.178256,3.309097e+06,1.189917e+06,1.035840e+06,269969.307031,6.710569e+06,6.345423e+06,6.725218e+06,6.359490e+06,2.439675e+08,4.782700e+06,2.432050e+08,4.769004e+06,1.127635e+07,2.441421e+08
min,6.917538e+18,0.000000,0.000000,7.142000e+03,2.040471e+14,3.360100e+10,4.400152e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,7.142988e+06,1.000000,1.000000,1.200000e+01,0.000000,2.070000e+02,3.000000e+00,1.400000e+01,2.000000,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,7.349883e+18,250.000000,251.000000,5.744200e+04,2.082014e+14,3.365151e+10,3.546261e+13,35.000000,3.000000,43.000000,47.000000,91.000000,0.000000,0.000000,0.000000,99.000000,0.000000,0.000000,0.000000,1.487800e+04,2.154000e+04,5.744206e+07,88.000000,107.000000,8.991480e+05,16448.000000,2.882393e+06,1.024279e+06,8.927930e+05,233383.000000,5.833501e+06,5.517965e+06,5.777156e+06,5.475981e+06,2.104733e+08,4.128476e+06,2.101869e+08,4.145943e+06,3.322203e+07,2.431072e+08
50%,7.349883e+18,499.000000,500.000000,8.639900e+04,2.082015e+14,3.366380e+10,3.572241e+13,54.000000,7.000000,63.000000,63.000000,100.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,3.930500e+04,4.679400e+04,8.639998e+07,205.000000,220.000000,1.794369e+06,32920.000000,5.765829e+06,2.054573e+06,1.793505e+06,466250.000000,1.161602e+07,1.101345e+07,1.164222e+07,1.099638e+07,4.234081e+08,8.291208e+06,4.218030e+08,8.267071e+06,4.114324e+07,4.558409e+08
75%,1.304243e+19,749.000000,750.000000,1.324300e+05,2.082018e+14,3.368473e+10,8.611970e+13,109.795706,17.662883,19710.000000,1120.000000,100.000000,4.000000,1.000000,1.000000,100.000000,0.000000,0.000000,0.000000,6.796110e+05,5.991140e+05,1.324307e+08,2765.000000,2560.000000,2.694938e+06,49334.000000,8.623552e+06,3.088454e+06,2.689327e+06,700440.000000,1.744852e+07,1.651556e+07,1.747048e+07,1.650727e+07,6.331742e+08,1.243162e+07,6.316918e+08,1.238415e+07,4.903424e+07,6.657051e+08
max,1.318654e+19,999.000000,999.000000,1.859336e+06,2.140743e+14,8.823971e+14,9.900120e+13,96923.000000,7120.000000,378160.000000,58613.000000,100.000000,93.000000,100.000000,94.000000,100.000000,98.000000,100.000000,96.000000,1.365365e+08,1.449113e+08,1.859336e+09,604061.000000,604122.000000,3.586064e+06,65870.000000,1.146283e+07,4.121357e+06,3.586146e+06,936418.000000,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

In [57]:
tel.skew()

Bearer Id                           0.026755
Start ms                            0.000968
End ms                             -0.001163
Dur. (ms)                           3.952622
IMSI                               41.124164
MSISDN/Number                     333.342413
IMEI                                1.073519
Avg RTT DL (ms)                    69.705161
Avg RTT UL (ms)                    31.530109
Avg Bearer TP DL (kbps)             2.589445
Avg Bearer TP UL (kbps)             4.503428
DL TP < 50 Kbps (%)                -2.303600
50 Kbps < DL TP < 250 Kbps (%)      3.279706
250 Kbps < DL TP < 1 Mbps (%)       4.577678
DL TP > 1 Mbps (%)                  5.383899
UL TP < 10 Kbps (%)                -9.008830
10 Kbps < UL TP < 50 Kbps (%)      10.972894
50 Kbps < UL TP < 300 Kbps (%)     21.936483
UL TP > 300 Kbps (%)               36.269930
Activity Duration DL (ms)           5.872275
Activity Duration UL (ms)           7.382581
Dur. (ms).1                         3.952622
Nb of sec with Vol DL < 6250B       9.065007
Nb of sec with Vol UL < 1250B       7.515066
Social Media DL (Bytes)            -0.002136
Social Media UL (Bytes)            -0.000359
Google DL (Bytes)                  -0.008092
Google UL (Bytes)                   0.002216
Email DL (Bytes)                   -0.002463
Email UL (Bytes)                    0.007358
Youtube DL (Bytes)                  0.000231
Youtube UL (Bytes)                 -0.001142
Netflix DL (Bytes)                 -0.002442
Netflix UL (Bytes)                 -0.000113
Gaming DL (Bytes)                  -0.003460
Gaming UL (Bytes)                  -0.001840
Other DL (Bytes)                    0.001400
Other UL (Bytes)                    0.001392
Total UL (Bytes)                   -0.002456
Total DL (Bytes)                   -0.003153
dtype: float64

In [55]:
tel.kurtosis()

Bearer Id                             -1.988473
Start ms                              -1.197441
End ms                                -1.199123
Dur. (ms)                             37.022454
IMSI                               55948.725267
MSISDN/Number                     116673.654352
IMEI                                  -0.703064
Avg RTT DL (ms)                     8805.687875
Avg RTT UL (ms)                     1632.646032
Avg Bearer TP DL (kbps)                9.573691
Avg Bearer TP UL (kbps)               25.086860
DL TP < 50 Kbps (%)                    5.659109
50 Kbps < DL TP < 250 Kbps (%)        16.009382
250 Kbps < DL TP < 1 Mbps (%)         34.546792
DL TP > 1 Mbps (%)                    41.020303
UL TP < 10 Kbps (%)                  113.043239
10 Kbps < UL TP < 50 Kbps (%)        176.420129
50 Kbps < UL TP < 300 Kbps (%)       673.037835
UL TP > 300 Kbps (%)                1763.889593
Activity Duration DL (ms)             48.112756
Activity Duration UL (ms)             81.140982
Dur. (ms).1                           37.022470
Nb of sec with Vol DL < 6250B        286.987789
Nb of sec with Vol UL < 1250B        192.907411
Social Media DL (Bytes)               -1.202894
Social Media UL (Bytes)               -1.200523
Google DL (Bytes)                     -1.203347
Google UL (Bytes)                     -1.200478
Email DL (Bytes)                      -1.200583
Email UL (Bytes)                      -1.195284
Youtube DL (Bytes)                    -1.200619
Youtube UL (Bytes)                    -1.198379
Netflix DL (Bytes)                    -1.205527
Netflix UL (Bytes)                    -1.202847
Gaming DL (Bytes)                     -1.203298
Gaming UL (Bytes)                     -1.202683
Other DL (Bytes)                      -1.197083
Other UL (Bytes)                      -1.191966
Total UL (Bytes)                      -0.327436
Total DL (Bytes)                      -1.198363
dtype: float64

In [56]:
#IQR
#calculate interquartile range 
q3, q1 = np.percentile(tel, [75 ,25])
iqr = q3 - q1
#display interquartile range 
iqr

TypeError: '<' not supported between instances of 'str' and 'float'